In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset=dataset.drop("User ID",axis=1)
print(dataset)
dataset["Purchased"].value_counts()
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset[["Purchased"]]

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid={"criterion":["gini",'entropy'],'splitter':['best','random'],
            "max_features":['auto','sqrt','log2']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,cv=5,n_jobs=-1,scoring="f1_weighted")
grid.fit(X_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   16.8s
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:   19.7s finished
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [9]:
re=grid.cv_results_
grid_predict=grid.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predict)

In [21]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.96      0.90      0.93        79
           1       0.83      0.93      0.87        41

    accuracy                           0.91       120
   macro avg       0.89      0.91      0.90       120
weighted avg       0.91      0.91      0.91       120

In [12]:
print(cm)

[[71  8]
 [ 8 33]]

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003125,0.006251,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.855956,0.859649,0.821429,0.890909,0.908566,0.867002,0.030047,2
1,0.009374,0.012499,0.006251,0.007656,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.891967,0.807902,0.824958,0.852738,0.871992,0.849823,0.030678,3
2,0.003429,0.006858,0.000000,0.000000,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.763925,0.824561,0.823129,0.856749,0.907273,0.834501,0.046877,6
3,0.003126,0.006252,0.003125,0.006249,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.841261,0.807902,0.789152,0.835418,0.847453,0.824117,0.022134,9
4,0.003125,0.006250,0.003125,0.006250,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.715577,0.859649,0.840114,0.871992,0.850396,0.827020,0.057305,8
5,0.001200,0.002401,0.000976,0.001952,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.842829,0.783934,0.824293,0.837173,0.890909,0.835466,0.034366,5
6,0.003125,0.006250,0.006251,0.007656,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.800244,0.805986,0.769053,0.927935,0.909541,0.841726,0.063481,4
7,0.006250,0.007655,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.824561,0.859649,0.733523,0.800990,0.873357,0.818451,0.049475,11
8,0.006249,0.007653,0.000000,0.000000,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.836563,0.787055,0.787755,0.856749,0.850396,0.823405,0.030330,10
9,0.012521,0.018225,0.003125,0.006250,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.826042,0.842829,0.737667,0.854545,0.908566,0.833593,0.055314,7
10,0.003125,0.006250,0.006256,0.007661,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.858037,0.860834,0.823129,0.927935,0.908566,0.875280,0.037539,1
11,0.003133,0.006267,0.006248,0.007652,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.735435,0.805986,0.789152,0.871992,0.758911,0.791976,0.046527,12

In [15]:
Future_predict=grid.predict([[40,30000,1]])
Future_predict

array([0], dtype=int64)