In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
dataset=dataset.drop("User ID",axis=1)
print(dataset)
dataset["Purchased"].value_counts()
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset[["Purchased"]]

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={"criterion":["gini",'entropy'],
            "max_features":['auto','sqrt','log2'],"n_estimators":[10,100]}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring="f1")
grid.fit(X_train,y_train)

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 12 candidates, totalling 36 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   24.6s
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:   26.0s finished
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:715: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1', verbose=3)

In [8]:
re=grid.cv_results_
grid_predict=grid.predict(x_test)

In [9]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predict)

In [21]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.96      0.90      0.93        79
           1       0.83      0.93      0.87        41

    accuracy                           0.91       120
   macro avg       0.89      0.91      0.90       120
weighted avg       0.91      0.91      0.91       120

In [10]:
print(cm)

[[72  7]
 [ 5 36]]

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.146994,0.120802,0.008907,4.832726e-03,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.811594,0.794118,0.865672,0.823751,0.030413,8
1,0.328739,0.047453,0.026606,8.467851e-03,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.794118,0.816901,0.865672,0.825451,0.029853,7
2,1.449370,1.974386,0.005000,5.150430e-07,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.750000,0.771429,0.857143,0.792704,0.046279,12
3,0.342957,0.054645,0.035401,6.801944e-03,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.811594,0.816901,0.882353,0.836859,0.032156,4
4,0.092251,0.052558,0.004663,4.705282e-04,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.738462,0.833333,0.830769,0.800632,0.044209,11
5,0.254404,0.035955,0.044988,6.288265e-03,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.828571,0.849315,0.865672,0.847784,0.015198,2
6,0.103790,0.085311,0.004161,2.291119e-04,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.794118,0.845070,0.830769,0.823215,0.021490,9
7,0.271875,0.014423,0.029609,8.026706e-03,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.828571,0.816901,0.848485,0.831309,0.013017,5
8,0.081281,0.040797,0.005169,8.517308e-04,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.750000,0.837838,0.895522,0.827509,0.059906,6
9,0.249029,0.035052,0.018704,1.728840e-03,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.828571,0.816901,0.865672,0.837018,0.020762,3
10,0.176327,0.094169,0.004128,1.830910e-04,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.738462,0.816901,0.892308,0.815614,0.062869,10
11,0.299576,0.050297,0.029498,1.004887e-02,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.828571,0.816901,0.898551,0.847938,0.036010,1

In [12]:
Future_predict=grid.predict([[40,30000,1]])
Future_predict

array([0], dtype=int64)